[package]
name = "pest_generator"
description = "pest's derive macro"
version = "2.0.0"
authors = ["Dragoș Tiselice <dragostiselice@gmail.com>"]
homepage = "https://pest-parser.github.io/"
repository = "https://github.com/pest-parser/pest"
documentation = "https://docs.rs/pest"
keywords = ["pest", "parser", "peg", "grammar"]
categories = ["parsing"]
license = "MIT/Apache-2.0"
readme = "_README.md"

[lib]
name = "pest_generator"

[dependencies]
pest = { path = "../pest", version = "2.0" }
pest_meta = { path = "../meta", version = "2.0" }
proc-macro2 = "0.4.4"
quote = "0.6.3"
syn = "0.14.1"

[badges]
codecov = { repository = "pest-parser/pest" }
maintenance = { status = "actively-developed" }
travis-ci = { repository = "pest-parser/pest" }
