sudo: required
language: rust
cache: cargo
os:
  - linux
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
addons:
  apt:
    packages:
      - libssl-dev
      - pkg-config
      - cmake
      - zlib1g-dev
git:
  depth: 1
branches:
  only:
    - staging
    - trying
    - master
notifications:
  email: false
install:
  - rustup component add clippy-preview
script:
  # Need a custom script because we are using cargo workspaces.
  - |
      cargo bootstrap && # dynamic build dependency of pest_meta
      cargo clippy --all --verbose -- -D clippy &&
      cargo build --all --verbose &&
      cargo test --all --verbose &&
      cargo doc --all --verbose
after_success:
  - |
      if [[ $TRAVIS_RUST_VERSION =~ nightly ]]; then
        RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
        cargo tarpaulin --out Xml &&
        bash <(curl -s https://codecov.io/bash)
      fi
