sudo: false
language: rust
cache: cargo
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly
  - 1.9.0
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
git:
  depth: 1
branches:
  only:
    - master
notifications:
  email: false
cache:
  directories:
    - $TRAVIS_BUILD_DIR/target
    - $HOME/.cargo
before_script:
  - |
    if [[ $TRAVIS_OS_NAME =~ linux ]]; then
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH
    fi
script:
  - |
    if [[ $TRAVIS_OS_NAME =~ linux ]]; then
      travis-cargo test &&
      travis-cargo --only stable doc &&
      python -c '
    import os
    import re

    for path, subdirs, files in os.walk("."):
        for name in files:
            if "macro" in name:
                with open(os.path.join(path, name), "r") as inputfile:
                    out = re.sub(" *\( (<[^>]*>)?@((?!\{ \.\.\. \};)(.|\\n))*{ \.\.\. \};\\n", "",
                                 inputfile.read())

                with open(os.path.join(path, name), "w") as outputfile:
                    outputfile.write(out)
      '
    else
      cargo test
    fi
after_success: |
  if [[ $TRAVIS_OS_NAME =~ linux && $TRAVIS_RUST_VERSION =~ stable ]]; then
    travis-cargo coveralls --no-sudo --verify \
    --kcov-options="--exclude-path=target/,tests/"
  fi
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
