sudo: false
language: rust
cache: cargo
os:
  - linux
rust:
  - stable
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake
git:
  depth: 1
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - |
      cargo install --force cargo-travis &&
      export PATH=$HOME/.cargo/bin:$PATH
script:
  # Need a custom script because we are using cargo workspaces.
  - |
      cargo build --all --verbose &&
      cargo test --all --verbose &&
      cargo doc --all --verbose
after_success:
  - |
      cargo coverage -m ../kcov --all
      bash <(curl -s https://codecov.io/bash)
