[package]
name = "pest_meta"
description = "pest meta language parser and validator"
version = "2.0.0"
authors = ["Dragoș Tiselice <dragostiselice@gmail.com>"]
repository = "https://github.com/pest-parser/pest"
documentation = "https://docs.rs/pest"
keywords = ["pest", "parser", "peg", "grammar"]
categories = ["parsing"]
license = "MIT/Apache-2.0"
readme = "_README.md"

[dependencies]
maplit = "^0.1.5"
# TODO: When we get 2.0.0 released to crates.io, we will want to bump this to "^2.0".
pest = "^1.0"
pest_derive = "^1.0"

[badges]
codecov = { repository = "pest-parser/pest" }
maintenance = { status = "actively-developed" }
travis-ci = { repository = "pest-parser/pest" }
