[package]
name = "pest_meta"
version = "1.0.0-beta.15"
authors = ["Victor-Nicolae Savu <victor.nicolae.savu@gmail.com>"]
repository = "https://github.com/pest-parser/pest"
documentation = "https://docs.rs/pest"
keywords = ["pest", "parser", "peg", "grammar"]
categories = ["parsing"]
license = "MPL-2.0"
readme = "_README.md"

[dependencies]
quote = "^0.3"
maplit = "^0.1.5"
pest = { path = "../pest", version = "^1.0.0-beta" }
